# Anthropic TypeScript SDK. HAND-AUTHORED - recipetool cannot generate this one.
#
# E1: `recipetool create` dies on this tree with
#   File "scripts/lib/recipetool/create.py", line 985, in handle_license_vars
#     if expression := extravalues.pop('LICENSE', '').strip():
#   AttributeError: 'set' object has no attribute 'strip'
# The npm handler puts a SET in extravalues['LICENSE'] and create.py assumes a
# string. That is a live defect in OE-Core at our pinned SHA - the third found in
# this estate, beside distutils3 removal and the PACKAGECONFIG-extras parse break.
# The bootstrap is NOT patched; the recipe is written by hand instead.
#
# The dependency closure is real, not hand-copied: npm-shrinkwrap.json was
# generated by `npm shrinkwrap` inside a DISPOSABLE `git archive` export of the
# acquired tree - never in the tree itself. An earlier attempt handed recipetool
# the acquired tree directly and npm wrote node_modules/ (3.0 MB) into pristine
# source, which is the R1 violation this arrangement exists to prevent.
#
# Closure: 2 declared runtime deps + 4 transitive, fully closed.
#   json-schema-to-ts -> @babel/runtime, ts-algebra
#   standardwebhooks  -> @stablelib/base64, fast-sha256
# The 26 devDependencies are excluded: NPM_INSTALL_DEV defaults to 0.

SUMMARY = "Anthropic TypeScript SDK"
HOMEPAGE = "https://github.com/anthropics/anthropic-sdk-typescript"

# MIT, read from the acquired tree (LICENSE: "Copyright 2023 Anthropic, PBC.").
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://LICENSE;md5=2453eb85b33e21e22cb4fa811c650d75"

inherit symoneural-pristine npm

SYMON_TREE = "/home/google/SymonSaysLLC/Symoneural-CLI/src/anthropic/source/anthropic-sdk-typescript"
SRCREV = "135f71e9297683e14614d4307081c0273ed0a09c"

# E4: five package tags share this commit (sdk-v0.125.0, aws-sdk-v0.7.1,
# bedrock-sdk-v0.33.5, foundry-sdk-v0.4.6, vertex-sdk-v0.19.8). PV follows the
# package THIS recipe builds - the main SDK, whose package.json says 0.125.0.
PV = "0.125.0"

# symoneural-pristine strips git://|gitsm:// from SRC_URI and lets do_fetch run
# for everything else, which is exactly what npmsw:// needs.
SRC_URI = "npmsw://${THISDIR}/${BPN}/npm-shrinkwrap.json"

NPM_INSTALL_DEV = "0"
