# Recipe created by recipetool
# This is the basis of a recipe and may need further editing in order to be fully functional.
# (Feel free to remove these comments when editing.)

# WARNING: the following LICENSE and LIC_FILES_CHKSUM values are best guesses - it is
# your responsibility to verify that the values are complete and correct.
#
# NOTE: multiple licenses have been detected; they have been separated with &
# in the LICENSE value for now since it is a reasonable assumption that all
# of the licenses apply. If instead there is a choice between the multiple
# licenses then you should change the value to separate the licenses with |
# instead of &. If there is any doubt, check the accompanying documentation
# to determine which situation is applicable.
# Built by symoneural-pristine: a DISPOSABLE `git archive` export of the
# acquired tree. ${S} is throwaway; the acquired tree is never written to.
# do_unpack asserts the tree HEAD equals SRCREV and refuses to build otherwise.
inherit symoneural-pristine
SYMON_TREE = "/home/google/SymonSaysLLC/Symoneural-Common/src/ml/source/tokenizers"

LICENSE = "Apache-2.0 AND MIT"
LIC_FILES_CHKSUM = "file://LICENSE;md5=86d3f3a95c324c9479bd8986968f4327 \
                    file://bindings/node/LICENSE;md5=195ddbbc20ae4e81cdc1d6b1c0d8846c \
                    file://tokenizers/LICENSE;md5=86d3f3a95c324c9479bd8986968f4327"

SRC_URI = "git://github.com/huggingface/tokenizers;protocol=https;nobranch=1;branch=master"

# Modify these as desired
# PV is the real upstream release tag at SRCREV, not recipetool's "1.0+git"
# placeholder. The placeholder is not merely cosmetic: it names every .ipk
# <pkg>_1.0+git-r0, and symoneural-pristine exports it as the wheel version
# via *_PRETEND_VERSION/*_BYPASS, where uv-dynamic-versioning parsed it and
# died with IndexError on int(parts[index]).
PV = "0.23.2"
SRCREV = "88a4498ad4ea1a9487b0a9b0ff881383fd5a06a3"

# NOTE: no Makefile found, unable to determine what needs to be done

# --- BUILD SYSTEM -------------------------------------------------------------
# Was a recipetool STUB: no build-system inherit, so bitbake ran bare `make`, and
# a ':' no-op do_install left an empty ${D} which R12 correctly failed.
#
# tokenizers is a Rust core with PyO3 Python bindings. The Python package lives in
# bindings/python and declares:
#     requires = ["maturin>=1.0,<2.0"]  /  build-backend = "maturin"
# OE's python3-maturin is 1.15.0, which satisfies that range.
#
# ${S} STAYS AT THE EXPORT ROOT. Moving it to bindings/python broke two things at
# once: LIC_FILES_CHKSUM anchors to ${S}, and re-anchoring those with ../../ then
# escaped the export, which symoneural-pristine's do_unpack assertion correctly
# rejected - "LIC_FILES_CHKSUM names 3 file(s) absent from the export". The class
# is stricter than stock OE here, and it is right to be.
#
# The proper lever is PEP517_SOURCE_PATH, which python_pep517 defines as
# `?= "${S}"` precisely so a package living in a subdirectory can be built without
# relocating ${S}. Same for the cargo half via CARGO_MANIFEST_PATH.
PEP517_SOURCE_PATH = "${S}/bindings/python"
CARGO_MANIFEST_PATH = "${S}/bindings/python/Cargo.toml"

inherit python_maturin cargo-update-recipe-crates

DEPENDS += "python3-maturin-native"

# Generated by: bitbake -c update_crates symoneural-tokenizers
# Pinned from bindings/python/Cargo.lock, tracked in git, so the crate closure is
# fixed and nothing is resolved from the network at build time.
require ${THISDIR}/symoneural-tokenizers-crates.inc
