# Recipe created by recipetool
# This is the basis of a recipe and may need further editing in order to be fully functional.
# (Feel free to remove these comments when editing.)

# WARNING: the following LICENSE and LIC_FILES_CHKSUM values are best guesses - it is
# your responsibility to verify that the values are complete and correct.
#
# The following license files were not able to be identified and are
# represented as "Unknown" below, you will need to check them yourself:
#   LICENSE.md
#
# NOTE: multiple licenses have been detected; they have been separated with &
# in the LICENSE value for now since it is a reasonable assumption that all
# of the licenses apply. If instead there is a choice between the multiple
# licenses then you should change the value to separate the licenses with |
# instead of &. If there is any doubt, check the accompanying documentation
# to determine which situation is applicable.
# LICENSE established from the licence text in the acquired tree. recipetool had
# emitted a non-SPDX token ('Unknown'/'Apache'), which newer OE-Core's SPDX parser
# rejects outright: do_populate_lic dies with
# "AttributeError: 'UnknownId' object has no attribute 'name'".
# Built by symoneural-pristine: a DISPOSABLE `git archive` export of the
# acquired tree. ${S} is throwaway; the acquired tree is never written to.
# do_unpack asserts the tree HEAD equals SRCREV and refuses to build otherwise.
inherit symoneural-pristine
SYMON_TREE = "/home/google/SymonSaysLLC/Symoneural-Crypto/src/stratum/source/stratum"

LICENSE = "Apache-2.0 AND MIT"
LIC_FILES_CHKSUM = "file://LICENSE-APACHE;md5=86d3f3a95c324c9479bd8986968f4327 \
                    file://LICENSE-MIT;md5=abd40148cf3f5fc7a8052c45980fa081 \
                    file://LICENSE.md;md5=14ecc01e3adadf9652f355df43b4855f"

SRC_URI = "git://github.com/stratum-mining/stratum;protocol=https;branch=main"

# Modify these as desired
PV = "1.0+git"
SRCREV = "c1a7991394254c806f97a5feb4f4be771596ce69"

# NOTE: no Makefile found, unable to determine what needs to be done





# Rust. cargo-update-recipe-crates provides the update_crates task, which writes
# the full crates.io closure into ${THISDIR} so it is tracked in git rather than
# resolved from the network at build time.
inherit cargo cargo-update-recipe-crates

# The crate closure, generated by `bitbake -c update_crates symoneural-stratum`.
require ${THISDIR}/symoneural-stratum-crates.inc
