# Recipe created by recipetool
# This is the basis of a recipe and may need further editing in order to be fully functional.
# (Feel free to remove these comments when editing.)

SUMMARY = "Transformers: the model-definition framework for state-of-the-art machine learning models in text, vision, audio, and multimodal models, for both inference and training."
HOMEPAGE = "https://github.com/huggingface/transformers"
# NOTE: License in setup.py/PKGINFO is: Apache 2.0 License
# WARNING: the following LICENSE and LIC_FILES_CHKSUM values are best guesses - it is
# your responsibility to verify that the values are complete and correct.
# Built by symoneural-pristine: a DISPOSABLE `git archive` export of the
# acquired tree. ${S} is throwaway; the acquired tree is never written to.
# do_unpack asserts the tree HEAD equals SRCREV and refuses to build otherwise.
inherit symoneural-pristine
SYMON_TREE = "/home/google/SymonSaysLLC/Symoneural-Common/src/ml/source/transformers"

LICENSE = "Apache-2.0"
LIC_FILES_CHKSUM = "file://LICENSE;md5=d15f16de23b5d7f8e28dd073d2ed8b28"

SRC_URI = "git://github.com/huggingface/transformers;protocol=https;branch=v5.17-release"

# Modify these as desired
PV = "5.17.0+git"
SRCREV = "856157a2f3e9594954310df18fdccc31ffddebe9"

inherit setuptools3

# WARNING: the following rdepends are determined through basic analysis of the
# python sources, and might not be 100% accurate.
RDEPENDS:${PN} += "python3-core"

# WARNING: We were unable to map the following python package/module
# dependencies to the bitbake packages which include them:
#    PIL
#    PIL.Image
#    _pytest
#    abc
#    accelerate
#    accelerate.state
#    accelerate.utils
#    argparse
#    ast
#    asyncio
#    attr
#    base64
#    check_docstrings
#    codecs
#    collections
#    collections.abc
#    concurrent.futures
#    contextlib
#    copy
#    dataclasses
#    datasets
#    datetime
#    deepspeed
#    deepspeed.ops.aio
#    deepspeed.utils
#    deepspeed.utils.zero_to_fp32
#    detectron2.structures.image_list
#    difflib
#    diffusers
#    doctest
#    enum
#    executorch.runtime
#    faiss
#    fetch_hub_objects_for_ci
#    functools
#    get_previous_daily_ci
#    git
#    glob
#    hashlib
#    http.server
#    httpx
#    huggingface_hub
#    huggingface_hub._snapshot_download
#    huggingface_hub.constants
#    huggingface_hub.dataclasses
#    huggingface_hub.errors
#    huggingface_hub.file_download
#    huggingface_hub.utils
#    importlib
#    importlib.metadata
#    importlib.util
#    inspect
#    io
#    jinja2
#    jinja2.exceptions
#    json
#    kernels
#    kernels.layer.layer
#    librosa
#    librosa.filters
#    liger_kernel.transformers
#    logging
#    mistral_common.exceptions
#    mistral_common.protocol.instruct.request
#    mistral_common.protocol.instruct.validator
#    mistral_common.protocol.transcription.request
#    mistral_common.tokens.tokenizers
#    mistral_common.tokens.tokenizers.base
#    mistral_common.tokens.tokenizers.mistral
#    mistral_common.tokens.tokenizers.tekken
#    mistral_common.tokens.tokenizers.utils
#    mlx.core
#    multiprocessing
#    numpy
#    onnxruntime
#    onnxruntime.transformers.io_binding_helper
#    optimum_benchmark
#    os
#    packaging
#    packaging.version
#    pandas
#    parameterized
#    pathlib
#    peft
#    pretty_midi
#    psutil
#    psycopg2
#    psycopg2.extensions
#    psycopg2.extras
#    pyctcdecode
#    pyctcdecode.decoder
#    pytest
#    queue
#    random
#    ray
#    ray.util.client.ray_client_helpers
#    re
#    requests
#    run_glue
#    run_translation
#    safetensors
#    safetensors.torch
#    sagemaker
#    sagemaker.huggingface
#    sentencepiece
#    shutil
#    signal
#    socket
#    soundfile
#    statistics
#    string
#    subprocess
#    tempfile
#    test_module.custom_configuration
#    test_module.custom_feature_extraction
#    test_module.custom_image_processing
#    test_module.custom_modeling
#    test_module.custom_pipeline
#    test_module.custom_processing
#    test_module.custom_tokenization
#    test_module.custom_tokenization_fast
#    test_module.custom_video_processing
#    textwrap
#    threading
#    tiktoken
#    timeout_decorator
#    timm
#    tokenizers
#    tokenizers.models
#    tokenizers.pre_tokenizers
#    torch
#    torch._dynamo
#    torch._dynamo.config
#    torch.distributed
#    torch.distributed.tensor
#    torch.distributed.tensor.placement_types
#    torch.multiprocessing
#    torch.multiprocessing.spawn
#    torch.nn
#    torch.nn.attention
#    torch.nn.attention.flex_attention
#    torch.nn.functional
#    torch.nn.parallel
#    torch.utils._pytree
#    torch.utils.data
#    torchao.quantization
#    torchaudio
#    torchcodec
#    torchvision
#    torchvision.transforms
#    tqdm
#    traceback
#    transformers
#    transformers.activations
#    transformers.audio_utils
#    transformers.backbone_utils
#    transformers.cache_utils
#    transformers.cli.add_new_model_like
#    transformers.configuration_utils
#    transformers.conversion_mapping
#    transformers.convert_slow_tokenizer
#    transformers.core_model_loading
#    transformers.data.data_collator
#    transformers.debug_utils
#    transformers.distributed
#    transformers.distributed.configuration_utils
#    transformers.distributed.fsdp
#    transformers.distributed.sharding_utils
#    transformers.distributed.tensor_parallel
#    transformers.distributed.utils
#    transformers.dynamic_module_utils
#    transformers.exporters
#    transformers.exporters.auto
#    transformers.exporters.base
#    transformers.exporters.configs
#    transformers.exporters.exporter_dynamo
#    transformers.exporters.exporter_executorch
#    transformers.exporters.exporter_onnx
#    transformers.exporters.utils
#    transformers.feature_extraction_utils
#    transformers.file_utils
#    transformers.fusion_mapping
#    transformers.generation
#    transformers.generation.candidate_generator
#    transformers.generation.configuration_utils
#    transformers.generation.continuous_batching.cache
#    transformers.generation.continuous_batching.cache_manager
#    transformers.generation.continuous_batching.continuous_api
#    transformers.generation.continuous_batching.distributed
#    transformers.generation.continuous_batching.input_outputs
#    transformers.generation.continuous_batching.offloading_manager
#    transformers.generation.continuous_batching.requests
#    transformers.generation.logits_process
#    transformers.generation.stopping_criteria
#    transformers.generation.utils
#    transformers.hf_argparser
#    transformers.hyperparameter_search
#    transformers.image_processing_backends
#    transformers.image_processing_utils
#    transformers.image_transforms
#    transformers.image_utils
#    transformers.initialization
#    transformers.integrations
#    transformers.integrations.accelerate
#    transformers.integrations.deepgemm
#    transformers.integrations.deepspeed
#    transformers.integrations.eager_paged
#    transformers.integrations.executorch
#    transformers.integrations.finegrained_fp8
#    transformers.integrations.heterogeneity
#    transformers.integrations.hub_kernels
#    transformers.integrations.integration_utils
#    transformers.integrations.liger
#    transformers.integrations.mistral
#    transformers.integrations.mistral.constants
#    transformers.integrations.mistral.tokenizer
#    transformers.integrations.moe
#    transformers.integrations.sdpa_attention
#    transformers.integrations.sdpa_paged
#    transformers.integrations.sonicmoe
#    transformers.integrations.tiktoken
#    transformers.loss
#    transformers.loss.loss_rnnt
#    transformers.loss.loss_tdt
#    transformers.loss.loss_utils
#    transformers.masking_utils
#    transformers.model_debugging_utils
#    transformers.modeling_flash_attention_utils
#    transformers.modeling_layers
#    transformers.modeling_outputs
#    transformers.modeling_utils
#    transformers.models.audio_spectrogram_transformer.feature_extraction_audio_spectrogram_transformer
#    transformers.models.auto
#    transformers.models.auto.auto_factory
#    transformers.models.auto.configuration_auto
#    transformers.models.auto.feature_extraction_auto
#    transformers.models.auto.image_processing_auto
#    transformers.models.auto.modeling_auto
#    transformers.models.auto.processing_auto
#    transformers.models.auto.tokenization_auto
#    transformers.models.auto.video_processing_auto
#    transformers.models.autoformer.modeling_autoformer
#    transformers.models.bark.generation_configuration_bark
#    transformers.models.bart.configuration_bart
#    transformers.models.bart.modeling_bart
#    transformers.models.bartpho.tokenization_bartpho
#    transformers.models.bert.configuration_bert
#    transformers.models.bert.tokenization_bert
#    transformers.models.bert.tokenization_bert_legacy
#    transformers.models.bert_japanese.tokenization_bert_japanese
#    transformers.models.bertweet.tokenization_bertweet
#    transformers.models.big_bird.tokenization_big_bird
#    transformers.models.bigbird_pegasus.modeling_bigbird_pegasus
#    transformers.models.biogpt.tokenization_biogpt
#    transformers.models.blenderbot.modeling_blenderbot
#    transformers.models.blenderbot.tokenization_blenderbot
#    transformers.models.blenderbot_small.modeling_blenderbot_small
#    transformers.models.blenderbot_small.tokenization_blenderbot_small
#    transformers.models.blt.modeling_blt
#    transformers.models.blt.modular_blt
#    transformers.models.camembert.tokenization_camembert
#    transformers.models.clip.modeling_clip
#    transformers.models.clip.tokenization_clip
#    transformers.models.codegen.tokenization_codegen
#    transformers.models.cohere_asr.modeling_cohere_asr
#    transformers.models.cohere_compass.image_processing_cohere_compass
#    transformers.models.cohere_compass.video_processing_cohere_compass
#    transformers.models.colmodernvbert.configuration_colmodernvbert
#    transformers.models.colmodernvbert.modeling_colmodernvbert
#    transformers.models.colmodernvbert.processing_colmodernvbert
#    transformers.models.colpali.configuration_colpali
#    transformers.models.colpali.modeling_colpali
#    transformers.models.colpali.processing_colpali
#    transformers.models.colqwen2.configuration_colqwen2
#    transformers.models.colqwen2.modeling_colqwen2
#    transformers.models.colqwen2.processing_colqwen2
#    transformers.models.conditional_detr.modeling_conditional_detr
#    transformers.models.cpm.tokenization_cpm
#    transformers.models.cpmant.tokenization_cpmant
#    transformers.models.ctrl.tokenization_ctrl
#    transformers.models.cwm
#    transformers.models.data2vec.modeling_data2vec_audio
#    transformers.models.data2vec.modeling_data2vec_text
#    transformers.models.deepseek_ocr2.configuration_deepseek_ocr2
#    transformers.models.deepseek_v2.modeling_deepseek_v2
#    transformers.models.detr.modeling_detr
#    transformers.models.dia
#    transformers.models.dia.modeling_dia
#    transformers.models.dinov3_vit.configuration_dinov3_vit
#    transformers.models.distilbert.modeling_distilbert
#    transformers.models.distilbert.tokenization_distilbert
#    transformers.models.dpr.configuration_dpr
#    transformers.models.dpr.tokenization_dpr
#    transformers.models.efficientloftr
#    transformers.models.efficientloftr.modeling_efficientloftr
#    transformers.models.eomt.modeling_eomt
#    transformers.models.ernie4_5_moe.modeling_ernie4_5_moe
#    transformers.models.ernie4_5_vl_moe.image_processing_ernie4_5_vl_moe
#    transformers.models.ernie4_5_vl_moe.video_processing_ernie4_5_vl_moe
#    transformers.models.esm.modeling_esm
#    transformers.models.esm.modeling_esmfold
#    transformers.models.esm.tokenization_esm
#    transformers.models.esmfold2.modeling_esmfold2
#    transformers.models.esmfold2.protein_utils
#    transformers.models.fastspeech2_conformer
#    transformers.models.flaubert.modeling_flaubert
#    transformers.models.flaubert.tokenization_flaubert
#    transformers.models.flava.image_processing_flava
#    transformers.models.fsmt.modeling_fsmt
#    transformers.models.fsmt.tokenization_fsmt
#    transformers.models.gemma.tokenization_gemma
#    transformers.models.gemma3.modeling_gemma3
#    transformers.models.gemma3n
#    transformers.models.gemma4.configuration_gemma4
#    transformers.models.gemma4.image_processing_pil_gemma4
#    transformers.models.gemma4.modeling_gemma4
#    transformers.models.gemma4_unified.modeling_gemma4_unified
#    transformers.models.glm46v.video_processing_glm46v
#    transformers.models.glm4v.image_processing_glm4v
#    transformers.models.glm4v.video_processing_glm4v
#    transformers.models.glm5_next.configuration_glm5_next
#    transformers.models.glm5_next.image_processing_glm5_next
#    transformers.models.glm5_next.modeling_glm5_next
#    transformers.models.glm5_next.video_processing_glm5_next
#    transformers.models.glmasr.configuration_glmasr
#    transformers.models.gpt2.modeling_gpt2
#    transformers.models.gpt2.tokenization_gpt2
#    transformers.models.gpt_bigcode.modeling_gpt_bigcode
#    transformers.models.gpt_neox.tokenization_gpt_neox
#    transformers.models.gpt_neox_japanese.tokenization_gpt_neox_japanese
#    transformers.models.grounding_dino.modeling_grounding_dino
#    transformers.models.hubert.modeling_hubert
#    transformers.models.hunyuan_vl.image_processing_hunyuan_vl
#    transformers.models.hunyuan_vl.image_processing_pil_hunyuan_vl
#    transformers.models.hunyuan_vl.processing_hunyuan_vl
#    transformers.models.hy_v3.modeling_hy_v3
#    transformers.models.ibert.modeling_ibert
#    transformers.models.idefics.configuration_idefics
#    transformers.models.idefics3
#    transformers.models.informer.modeling_informer
#    transformers.models.jina_embeddings_v3
#    transformers.models.kimi_k25.video_processing_kimi_k25
#    transformers.models.kosmos2.configuration_kosmos2
#    transformers.models.kosmos2_5.configuration_kosmos2_5
#    transformers.models.layoutlmv2
#    transformers.models.layoutlmv2.tokenization_layoutlmv2
#    transformers.models.layoutlmv3
#    transformers.models.layoutlmv3.tokenization_layoutlmv3
#    transformers.models.layoutxlm
#    transformers.models.led.modeling_led
#    transformers.models.lfm2_vl.image_processing_lfm2_vl
#    transformers.models.lfm2_vl.modeling_lfm2_vl
#    transformers.models.lightglue.configuration_lightglue
#    transformers.models.lightglue.modeling_lightglue
#    transformers.models.llama
#    transformers.models.llama.modeling_llama
#    transformers.models.llama.tokenization_llama
#    transformers.models.llava_next.image_processing_llava_next
#    transformers.models.llava_next.modeling_llava_next
#    transformers.models.longformer.modeling_longformer
#    transformers.models.m2m_100.modeling_m2m_100
#    transformers.models.m2m_100.tokenization_m2m_100
#    transformers.models.mamba2.modeling_mamba2
#    transformers.models.marian.modeling_marian
#    transformers.models.marian.tokenization_marian
#    transformers.models.markuplm.tokenization_markuplm
#    transformers.models.mask2former.image_processing_mask2former
#    transformers.models.mask2former.modeling_mask2former
#    transformers.models.maskformer
#    transformers.models.maskformer.image_processing_maskformer
#    transformers.models.maskformer.modeling_maskformer
#    transformers.models.mbart.modeling_mbart
#    transformers.models.mgp_str.tokenization_mgp_str
#    transformers.models.minicpmv4_6.configuration_minicpmv4_6
#    transformers.models.minimax.modeling_minimax
#    transformers.models.minimax_m3_vl.modeling_minimax_m3_vl
#    transformers.models.mistral.configuration_mistral
#    transformers.models.mistral.modeling_mistral
#    transformers.models.mixtral.configuration_mixtral
#    transformers.models.mixtral.modeling_mixtral
#    transformers.models.mllama.configuration_mllama
#    transformers.models.mluke.tokenization_mluke
#    transformers.models.mobilevitv2.modeling_mobilevitv2
#    transformers.models.moonshine.modeling_moonshine
#    transformers.models.moonshine_streaming.modeling_moonshine_streaming
#    transformers.models.mpnet.tokenization_mpnet
#    transformers.models.muse_glimmer.configuration_muse_glimmer
#    transformers.models.muse_glimmer.image_processing_muse_glimmer
#    transformers.models.muse_glimmer.modeling_muse_glimmer
#    transformers.models.muse_glimmer.video_processing_muse_glimmer
#    transformers.models.muse_glimmer_assistant.modeling_muse_glimmer_assistant
#    transformers.models.mvp.modeling_mvp
#    transformers.models.neomme.modeling_neomme
#    transformers.models.nllb.tokenization_nllb
#    transformers.models.nllb_moe.modeling_nllb_moe
#    transformers.models.nougat.tokenization_nougat
#    transformers.models.olmo_hybrid.modeling_olmo_hybrid
#    transformers.models.omdet_turbo.modeling_omdet_turbo
#    transformers.models.oneformer.image_processing_oneformer
#    transformers.models.oneformer.modeling_oneformer
#    transformers.models.openai_privacy_filter.configuration_openai_privacy_filter
#    transformers.models.paddleocr_vl.image_processing_paddleocr_vl
#    transformers.models.parakeet
#    transformers.models.parakeet.modeling_parakeet
#    transformers.models.patchtsmixer.modeling_patchtsmixer
#    transformers.models.pegasus.modeling_pegasus
#    transformers.models.pegasus_x.modeling_pegasus_x
#    transformers.models.phobert.tokenization_phobert
#    transformers.models.plbart.modeling_plbart
#    transformers.models.pp_chart2table
#    transformers.models.prophetnet.modeling_prophetnet
#    transformers.models.prophetnet.tokenization_prophetnet
#    transformers.models.qwen2.tokenization_qwen2
#    transformers.models.qwen2_5_omni.configuration_qwen2_5_omni
#    transformers.models.qwen2_5_omni.modeling_qwen2_5_omni
#    transformers.models.qwen2_vl.image_processing_qwen2_vl
#    transformers.models.qwen2_vl.video_processing_qwen2_vl
#    transformers.models.qwen3
#    transformers.models.qwen3_5.configuration_qwen3_5
#    transformers.models.qwen3_5.modeling_qwen3_5
#    transformers.models.qwen3_asr.modeling_qwen3_asr
#    transformers.models.qwen3_asr.processing_qwen3_asr
#    transformers.models.qwen3_next.modeling_qwen3_next
#    transformers.models.qwen3_omni_moe.configuration_qwen3_omni_moe
#    transformers.models.qwen3_vl.configuration_qwen3_vl
#    transformers.models.qwen3_vl.modeling_qwen3_vl
#    transformers.models.qwen3_vl.video_processing_qwen3_vl
#    transformers.models.qwen3_vl_moe.configuration_qwen3_vl_moe
#    transformers.models.rag.configuration_rag
#    transformers.models.rag.retrieval_rag
#    transformers.models.rag.tokenization_rag
#    transformers.models.reformer.modeling_reformer
#    transformers.models.reformer.tokenization_reformer
#    transformers.models.roberta.configuration_roberta
#    transformers.models.roberta.modeling_roberta
#    transformers.models.roberta.tokenization_roberta
#    transformers.models.roberta_prelayernorm.modeling_roberta_prelayernorm
#    transformers.models.roc_bert.tokenization_roc_bert
#    transformers.models.roformer.modeling_roformer
#    transformers.models.sam.image_processing_sam
#    transformers.models.sam3.configuration_sam3
#    transformers.models.sam3.image_processing_sam3
#    transformers.models.sam3.modeling_sam3
#    transformers.models.sam3.processing_sam3
#    transformers.models.sam3_lite_text.configuration_sam3_lite_text
#    transformers.models.sam3_lite_text.modeling_sam3_lite_text
#    transformers.models.sapiens2.modeling_sapiens2
#    transformers.models.seamless_m4t
#    transformers.models.seggpt.modeling_seggpt
#    transformers.models.shieldgemma2.modeling_shieldgemma2
#    transformers.models.slanet.modeling_slanet
#    transformers.models.speech_to_text
#    transformers.models.speech_to_text.feature_extraction_speech_to_text
#    transformers.models.speech_to_text.modeling_speech_to_text
#    transformers.models.speech_to_text.tokenization_speech_to_text
#    transformers.models.speecht5
#    transformers.models.splinter.tokenization_splinter
#    transformers.models.step3p7.configuration_step3p7
#    transformers.models.superglue.configuration_superglue
#    transformers.models.superglue.modeling_superglue
#    transformers.models.superpoint.configuration_superpoint
#    transformers.models.superpoint.modeling_superpoint
#    transformers.models.switch_transformers.modeling_switch_transformers
#    transformers.models.tapas.modeling_tapas
#    transformers.models.tapas.tokenization_tapas
#    transformers.models.time_series_transformer.modeling_time_series_transformer
#    transformers.models.tipsv2_dpt.modeling_tipsv2_dpt
#    transformers.models.trocr.modeling_trocr
#    transformers.models.video_llama_3.image_processing_video_llama_3
#    transformers.models.video_llama_3.video_processing_video_llama_3
#    transformers.models.videomt.modeling_videomt
#    transformers.models.videoprism.modeling_videoprism
#    transformers.models.vits.tokenization_vits
#    transformers.models.voxtral_realtime.configuration_voxtral_realtime
#    transformers.models.wav2vec2
#    transformers.models.wav2vec2.modeling_wav2vec2
#    transformers.models.wav2vec2.tokenization_wav2vec2
#    transformers.models.wav2vec2_bert
#    transformers.models.wav2vec2_bert.modeling_wav2vec2_bert
#    transformers.models.wav2vec2_conformer.modeling_wav2vec2_conformer
#    transformers.models.wav2vec2_phoneme.tokenization_wav2vec2_phoneme
#    transformers.models.wav2vec2_with_lm
#    transformers.models.wav2vec2_with_lm.processing_wav2vec2_with_lm
#    transformers.models.whisper
#    transformers.models.whisper.modeling_whisper
#    transformers.models.whisper.tokenization_whisper
#    transformers.models.xglm.tokenization_xglm
#    transformers.models.xlm.modeling_xlm
#    transformers.models.xlm.tokenization_xlm
#    transformers.models.xlm_roberta_xl.modeling_xlm_roberta_xl
#    transformers.models.xlnet.tokenization_xlnet
#    transformers.models.xlstm.modeling_xlstm
#    transformers.models.xmod.modeling_xmod
#    transformers.models.zaya.modeling_zaya
#    transformers.monkey_patching
#    transformers.optimization
#    transformers.pipelines
#    transformers.pipelines.audio_utils
#    transformers.pipelines.automatic_speech_recognition
#    transformers.pipelines.base
#    transformers.pipelines.document_question_answering
#    transformers.pipelines.pt_utils
#    transformers.processing_utils
#    transformers.pytorch_utils
#    transformers.quantizers.quantizer_finegrained_fp8
#    transformers.testing_utils
#    transformers.tokenization_mistral_common
#    transformers.tokenization_python
#    transformers.tokenization_utils_base
#    transformers.tokenization_utils_sentencepiece
#    transformers.tokenization_utils_tokenizers
#    transformers.trainer
#    transformers.trainer_callback
#    transformers.trainer_jit_checkpoint
#    transformers.trainer_optimizer
#    transformers.trainer_pt_utils
#    transformers.trainer_utils
#    transformers.training_args
#    transformers.utils
#    transformers.utils.attention_visualizer
#    transformers.utils.auto_docstring
#    transformers.utils.chat_parsing
#    transformers.utils.chat_parsing.response_parser
#    transformers.utils.chat_template_utils
#    transformers.utils.constants
#    transformers.utils.deprecation
#    transformers.utils.generic
#    transformers.utils.hp_naming
#    transformers.utils.hub
#    transformers.utils.import_utils
#    transformers.utils.logging
#    transformers.utils.network_logging
#    transformers.utils.notebook
#    transformers.utils.output_capturing
#    transformers.utils.type_validators
#    transformers.utils.versions
#    transformers.video_utils
#    types
#    typing
#    unidic
#    unittest
#    unittest.mock
#    unittest.util
#    urllib.request
#    utils.fetch_hub_objects_for_ci
#    uuid
#    warnings
#    weakref
#    yaml
