# SyMoNeuRaL-owned Cython. NOT a redesign: this mirrors OE-Core's
# python3-cython_3.2.9.bb, same upstream, repointed at the estate's own pinned tree.
# own pinned tree. LIC_FILES_CHKSUM matches OE's declaration byte for byte
# (61c3ee8961575861fa86c7e62bc9f69c), verified against our acquired LICENSE.txt.
#
# WHY OWN IT. scipy's extension modules are GENERATED by Cython, so the C that
# becomes RavenCalc's numerics is produced by this tool. Borrowing OE-Core's
# python3-cython meant the estate shipped code emitted by a compiler it neither
# pinned nor acquired - the D2 provider collision, one level further back than
# usual because it is a code generator rather than a library.
inherit symoneural-pristine
SYMON_TREE = "/home/google/SymonSaysLLC/Symoneural-Ravencalc/src/devtools/source/cython"

SUMMARY = "The Cython language"
HOMEPAGE = "https://cython.org"
DESCRIPTION = "Cython is a language specially designed for writing Python extension \
modules. It bridges the gap between the high-level world of Python and the low-level \
world of C."
SECTION = "devel/python"

LICENSE = "Apache-2.0"
LIC_FILES_CHKSUM = "file://LICENSE.txt;md5=61c3ee8961575861fa86c7e62bc9f69c"

SRC_URI = "git://github.com/cython/cython;protocol=https;branch=master"
SRCREV = "ec152091ca7c535e04b5da96e5bedfc9b33def22"
PV = "3.2.5"


# PINNED 3.2.5, NOT 3.2.9, and the constraint came from the build not from taste:
#   scipy         wants  Cython>=3.2.0,<3.3.0     -> 3.2.9 ok
#   scikit-learn  wants  cython>=3.1.2,<3.2.6     -> 3.2.9 REJECTED
# scikit-learn's pyproject even names the reason - cython issue #7846 - and
# excludes 3.2.6, 3.2.7, 3.2.8 and 3.2.9 explicitly. The intersection of the two
# consumers is >=3.2.0,<3.2.6, so 3.2.5 is the only version that satisfies both.
#
# Owning the recipe is what made this visible. Borrowing OE-Core's python3-cython
# would have meant taking whatever version OE happened to ship and discovering the
# conflict as an opaque "Unmet dependencies" failure with no lever to pull.

inherit setuptools3

# OE-Core carries 0001-Replace-not-predictable-build-path-prefix-with-hardc.patch
# to stop Cython writing absolute build paths into the .c it generates. We do NOT
# carry it: symoneural-pristine sets do_patch[noexec], because a patched tree is
# no longer the tree the SRCREV names.
#
# Nothing is lost. symoneural-scipy's do_compile:append rewrites build paths in
# EVERY generated source, not only Cython's, and is proven by the buildpaths QA
# check passing. The general fix at the consumer beats a per-generator patch.

# Kept VERBATIM from OE-Core's python3-cython recipe. I omitted this block when
# first writing the recipe and it broke numpy immediately:
#   ../pristine/meson.build:1:0: ERROR: Unknown compiler(s): [['cython3']]
#   Running `cython3 -V` gave "[Errno 2] No such file or directory: 'cython3'"
# OE's cython.bbclass tells meson to look for `cython3`, so the binaries must
# carry the 3 suffix. Ours installed plain `cython` and nothing found it.
#
# This is what "do not redesign, just append symoneural-" means in practice:
# mirroring a recipe means carrying its install-time behaviour too, not only its
# SRC_URI and LICENSE. An omission is a redesign.
do_install:append() {
    mv ${D}${bindir}/cython ${D}${bindir}/cython3
    mv ${D}${bindir}/cythonize ${D}${bindir}/cythonize3
    mv ${D}${bindir}/cygdb ${D}${bindir}/cygdb3
}

# Do not depend on OE-Core's cython to build our own.
DEPENDS:remove = "python3-cython-native"

RDEPENDS:${PN}:class-target += " \
    python3-misc python3-netserver python3-pkgutil python3-pyparsing \
    python3-setuptools python3-shell python3-xml \
"

BBCLASSEXTEND = "native nativesdk"
