# Recipe created by recipetool
# This is the basis of a recipe and may need further editing in order to be fully functional.
# (Feel free to remove these comments when editing.)

# WARNING: the following LICENSE and LIC_FILES_CHKSUM values are best guesses - it is
# your responsibility to verify that the values are complete and correct.
#
# The following license files were not able to be identified and are
# represented as "Unknown" below, you will need to check them yourself:
#   metadata/src/copyright.rs
#   protocol/proto/player_license.proto
#
# NOTE: multiple licenses have been detected; they have been separated with &
# in the LICENSE value for now since it is a reasonable assumption that all
# of the licenses apply. If instead there is a choice between the multiple
# licenses then you should change the value to separate the licenses with |
# instead of &. If there is any doubt, check the accompanying documentation
# to determine which situation is applicable.
# LICENSE established from the licence text in the acquired tree. recipetool had
# emitted a non-SPDX token ('Unknown'/'Apache'), which newer OE-Core's SPDX parser
# rejects outright: do_populate_lic dies with
# "AttributeError: 'UnknownId' object has no attribute 'name'".
# Built by symoneural-pristine: a DISPOSABLE `git archive` export of the
# acquired tree. ${S} is throwaway; the acquired tree is never written to.
# do_unpack asserts the tree HEAD equals SRCREV and refuses to build otherwise.
inherit symoneural-pristine
SYMON_TREE = "/home/google/SymonSaysLLC/Symoneural-Remix/src/librespot/source/librespot"

LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://LICENSE;md5=98b2b0c9a6081259c441045ca68b640f \
                    file://metadata/src/copyright.rs;md5=e9644593d31089f5d3b6f483392ec7dc \
                    file://protocol/proto/player_license.proto;md5=93b9409e7bf39ec20c06077d26c1d8c2"

SRC_URI = "git://github.com/librespot-org/librespot;protocol=https;branch=dev"

# Modify these as desired
# PV is the real upstream release tag at SRCREV, not recipetool's "1.0+git"
# placeholder. The placeholder is not merely cosmetic: it names every .ipk
# <pkg>_1.0+git-r0, and symoneural-pristine exports it as the wheel version
# via *_PRETEND_VERSION/*_BYPASS, where uv-dynamic-versioning parsed it and
# died with IndexError on int(parts[index]).
PV = "0.8.0"
SRCREV = "d36f9f1907e8cc9d68a93f8ebc6b627b1bf7267d"

# NOTE: no Makefile found, unable to determine what needs to be done

# --- BUILD SYSTEM -------------------------------------------------------------
# This recipe was a recipetool STUB. It inherited no build-system class at all, so
# bitbake fell through to base.bbclass and ran bare `make`, and its do_install was
# a ':' no-op. That produced an empty ${D}, which R12 correctly failed:
#   do_install produced an EMPTY ${D}. Nothing was installed, yet the task would
#   have reported success.
# The assertion did its job - this is a recipe defect, not a build failure.
#
# librespot is a Rust binary: Cargo.toml at the tree root, package "librespot",
# version 0.8.0, with a committed Cargo.lock.
#
# Pattern copied from symoneural-stratum, the estate's Rust recipe that already
# builds. cargo-update-recipe-crates provides the update_crates task, which writes
# the full crates.io closure into ${THISDIR} so it is TRACKED IN GIT rather than
# resolved from the network at build time - that is what keeps the build offline
# and the crate set pinned.
inherit cargo cargo-update-recipe-crates

# Generated by: bitbake -c update_crates symoneural-librespot
require ${THISDIR}/symoneural-librespot-crates.inc

# NATIVE LIBRARIES for the -sys crates in the closure.
# The crate set contains 23 *-sys crates, but most are gated behind features for
# other platforms (windows-sys, ndk-sys, js-sys, web-sys, core-foundation-sys) or
# are alternative audio backends not selected by default (jack, portaudio, sdl2,
# gstreamer, pulseaudio). Two are built for x86_64-linux with default features:
#
#   openssl-sys  -> openssl    (TLS to Spotify)
#   alsa-sys     -> alsa-lib   (the default Linux audio backend)
#
# pkgconfig is not optional here. openssl-sys's build script shells out to
# pkg-config and fails with "The pkg-config command could not be found" before it
# ever looks for the library, so DEPENDS alone is not enough.
inherit pkgconfig
DEPENDS += "alsa-lib"

# The `pkg_config` CRATE refuses to run at all when TARGET != HOST unless told
# otherwise, and it bails BEFORE looking for the library. openssl is correctly
# staged - openssl.pc and libssl.so.4 are both in recipe-sysroot - so DEPENDS and
# `inherit pkgconfig` were necessary but not sufficient.
export PKG_CONFIG_ALLOW_CROSS = "1"

# And refuse the fallback: openssl-sys will otherwise try to BUILD a vendored
# copy of OpenSSL from source inside the crate, which would ship a second openssl
# the estate does not pin - the provider collision, arriving through a crate.
export OPENSSL_NO_VENDOR = "1"

# --- TLS BACKEND: rustls, not native OpenSSL ---------------------------------
# openssl-sys 0.9.111 aborts against this estate's OpenSSL:
#   This crate is only compatible with OpenSSL (version 1.0.2 through 1.1.1, or
#   3), or LibreSSL 3.5 through 4.2.x, but a different version of OpenSSL was
#   found. The build is now aborting due to this version mismatch.
# OE-Core ships openssl 4.0.2. The crate supports up to 3.x. This is a genuine
# version wall, not a configuration problem - PKG_CONFIG_ALLOW_CROSS and
# OPENSSL_NO_VENDOR both reached the task (confirmed in run.do_compile) and
# openssl.pc and libssl.so.4 were both correctly staged.
#
# librespot's own Cargo.toml offers rustls for exactly this situation:
#   "Choose this for avoiding external OpenSSL dependencies, reproducible builds,
#    or when targeting platforms where native TLS dependencies are unavailable or
#    problematic"
# So this is a SUPPORTED UPSTREAM CONFIGURATION, not a patch - the same posture as
# scipy's -Duse-pythran=false. The pristine guarantee holds.
#
# Keeping default features would mean waiting for openssl-sys to support OpenSSL
# 4, or downgrading a security-critical library to satisfy a crate. Neither is
# acceptable.
CARGO_BUILD_FLAGS += "--no-default-features --features rustls-tls-native-roots,rodio-backend,with-libmdns"

# rustls-tls-native-roots reads the system certificate store at RUNTIME.
RDEPENDS:${PN} += "ca-certificates"
