# symoneural-cuda - the ONE way a recipe reaches CUDA in this estate (ruling
# cuda-toolkit-authority, P7, 2026-09-14: CUDA 13.4.1 for Blackwell sm_120).
#
# nvcc runs from the NATIVE sysroot; headers and libraries are linked from the
# TARGET sysroot; both come from the cuda-toolkit-bin recipe. Nothing here names
# /usr/local/cuda-* on the host, and no consumer should. libcuda.so.1 and
# libnvidia-ml.so.1 are host-driver-provided at run time (posture S2): the toolkit
# ships only the link-time stub.
#
# The host compiler nvcc drives is the estate's own cross g++ (GCC 16.2). nvcc 13.4
# accepts GCC <= 16 (crt/host_config.h: '#if __GNUC__ > 16' is the error), so no
# -allow-unsupported-compiler is passed - and none may be added here.
SYMON_CUDA_VERSION ?= "13.4"
SYMON_CUDA_ARCH ?= "120"

DEPENDS += "cuda-toolkit-bin cuda-toolkit-bin-native"

SYMON_CUDA_NATIVE = "${STAGING_DIR_NATIVE}${prefix_native}/local/cuda-${SYMON_CUDA_VERSION}"
SYMON_CUDA_TARGET = "${STAGING_DIR_HOST}${prefix}/local/cuda-${SYMON_CUDA_VERSION}"

# CMake consumers (torch, ggml, the probe) get the compiler, host compiler, root, arch
# and flags through OE's generated toolchain file - not EXTRA_OECMAKE, whose expansion
# is unquoted on the command line and cannot carry a multi-token flag string.
# The host side of every .cu file is compiled by the cross g++ with the SAME flags
# CMake gives C++ (OECMAKE_CXX_FLAGS: sysroot, tune, hardening, prefix maps), each
# forwarded through nvcc as -Xcompiler=<flag>; that is what keeps buildpaths QA clean
# for CUDA translation units.
# cmake-class consumers have OECMAKE_CXX_FLAGS (sysroot, tune, CXXFLAGS); consumers that
# drive CMake themselves (torch) have only CXXFLAGS - the wrapper below supplies sysroot
# and tune for them. Either way the prefix maps and hardening reach every .cu host side.
SYMON_CUDA_HOST_FLAGS = "${@' '.join('-Xcompiler=' + f for f in (d.getVar('OECMAKE_CXX_FLAGS') or d.getVar('CXXFLAGS') or '').split())}"

# nvcc calls the host compiler for host-side compilation AND for the final link, and
# -Xcompiler flags reach it only when compiling. OE's cross gcc has no usable default
# sysroot, so a bare link cannot find Scrt1.o or -lc. The host compiler nvcc sees is
# therefore a wrapper that prepends the sysroot, the tune and OE's LDFLAGS on every
# call; hardening/prefix-map flags for host-side compilation still travel through
# CMAKE_CUDA_FLAGS above.
SYMON_CUDA_HOST_CXX = "${WORKDIR}/symoneural-cuda-host-g++"
symon_cuda_write_host_cxx() {
	cat > ${SYMON_CUDA_HOST_CXX} <<EOF
#!/bin/sh
# generated by symoneural-cuda.bbclass - the host compiler nvcc drives, with the
# estate sysroot/tune/link flags on every invocation (compile and link)
exec ${STAGING_BINDIR_TOOLCHAIN}/${HOST_PREFIX}g++ --sysroot=${STAGING_DIR_HOST} ${TUNE_CCARGS} ${LDFLAGS} "\$@"
EOF
	chmod +x ${SYMON_CUDA_HOST_CXX}
}
# written before every consumer's configure, whichever build system drives nvcc
do_configure[prefuncs] += "symon_cuda_write_host_cxx"
cmake_do_generate_toolchain_file:append() {
	cat >> ${WORKDIR}/toolchain.cmake <<EOF

# symoneural-cuda: the estate CUDA authority (native nvcc, target headers/libraries)
set( CMAKE_CUDA_COMPILER "${SYMON_CUDA_NATIVE}/bin/nvcc" CACHE FILEPATH "estate nvcc from the native sysroot" )
set( CMAKE_CUDA_HOST_COMPILER "${SYMON_CUDA_HOST_CXX}" CACHE FILEPATH "estate cross g++ with sysroot/tune/ldflags" )
set( CMAKE_CUDA_ARCHITECTURES "${SYMON_CUDA_ARCH}" CACHE STRING "compute capability targets" )
set( CUDAToolkit_ROOT "${SYMON_CUDA_TARGET}" CACHE PATH "estate toolkit in the target sysroot" )
set( CMAKE_CUDA_FLAGS "${SYMON_CUDA_HOST_FLAGS}" CACHE STRING "host-side flags forwarded through nvcc" )
EOF
}

# Consumers that drive CMake themselves (torch's PEP 517 backend) append this to
# their CMAKE_ARGS. No CMAKE_CUDA_ARCHITECTURES here: torch rejects it and wants the
# dotted form in TORCH_CUDA_ARCH_LIST (SYMON_CUDA_ARCH_DOTTED); no CMAKE_CUDA_FLAGS
# either - such consumers own their own flag assembly.
SYMON_CUDA_ARCH_DOTTED = "${@'%s.%s' % (d.getVar('SYMON_CUDA_ARCH')[:-1], d.getVar('SYMON_CUDA_ARCH')[-1])}"
# CUDA_TOOLKIT_ROOT_DIR is for the legacy FindCUDA module torch still calls first: it
# derives the root only from CUDA_PATH/CUDA_BIN_PATH or an nvcc on PATH, none of which
# exist here (P7 C7 first configure: "Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR)").
SYMON_CUDA_CMAKE_ARGS = "-DCMAKE_CUDA_COMPILER=${SYMON_CUDA_NATIVE}/bin/nvcc -DCMAKE_CUDA_HOST_COMPILER=${SYMON_CUDA_HOST_CXX} -DCUDAToolkit_ROOT=${SYMON_CUDA_TARGET} -DCUDA_TOOLKIT_ROOT_DIR=${SYMON_CUDA_TARGET}"
# non-CMake consumers read these; CMake itself seeds CMAKE_CUDA_COMPILER,
# CMAKE_CUDA_HOST_COMPILER and CMAKE_CUDA_FLAGS from CUDACXX, CUDAHOSTCXX and CUDAFLAGS
# when no toolchain file sets them (torch's PEP 517 build)
export CUDACXX = "${SYMON_CUDA_NATIVE}/bin/nvcc"
export CUDAHOSTCXX = "${SYMON_CUDA_HOST_CXX}"
export CUDAFLAGS = "${SYMON_CUDA_HOST_FLAGS}"
export CUDA_HOME = "${SYMON_CUDA_TARGET}"
# torch's vendored legacy FindCUDA (cmake/Modules_CUDA_fix/upstream): when cross-compiling
# for x86_64 it never derives CUDA_TOOLKIT_TARGET_DIR from a pre-set root, so its
# NO_DEFAULT_PATH probes search nothing and its fallback would search the HOST's default
# library paths. Its documented environment inputs make the probes deterministic instead:
# CUDA_PATH feeds the include/library probes (ENV CUDA_PATH + PATH_SUFFIXES include|lib64)
# and CUDA_NVCC_EXECUTABLE is taken verbatim as the compiler it reports on.
export CUDA_PATH = "${SYMON_CUDA_TARGET}"
export CUDA_NVCC_EXECUTABLE = "${SYMON_CUDA_NATIVE}/bin/nvcc"
export CUDAARCHS = "${SYMON_CUDA_ARCH}"

# ---- S2: the driver boundary, stated once for every consumer ----------------------
# libcuda.so.1 and libnvidia-ml.so.1 belong to the host driver. No package in the feed
# provides them and none may; a consumer that links them cannot satisfy OE's
# file-rdeps check for those two names. That check is therefore exempted for the
# consumer's packages - and REPLACED by symon_cuda_qa_s2 below, which walks every ELF
# in every package and fails the build if any NEEDED library other than the S2 pair
# has no provider in this build's shared-library registry. Nothing else is hidden.
SYMON_CUDA_S2_LIBS = "libcuda.so.1 libnvidia-ml.so.1"
PRIVATE_LIBS:${PN} += "${SYMON_CUDA_S2_LIBS}"
INSANE_SKIP:${PN} += "file-rdeps"

python symon_cuda_qa_s2() {
    import os, glob, subprocess
    pkgdest = d.getVar('PKGDEST'); pkgdata = d.getVar('PKGDATA_DIR'); readelf = d.getVar('READELF')
    s2 = set(d.getVar('SYMON_CUDA_S2_LIBS').split())
    providers = set()
    for lst in glob.glob(os.path.join(pkgdata, 'shlibs2', '*.list')):
        with open(lst) as fh:
            for line in fh:
                providers.add(line.split(':', 1)[0].strip())
    checked, s2_entries, unresolved, s2_used = 0, 0, [], set()
    for pkg in d.getVar('PACKAGES').split():
        root = os.path.join(pkgdest, pkg)
        for dp, _, fns in os.walk(root):
            for fn in fns:
                p = os.path.join(dp, fn)
                if os.path.islink(p) or not os.path.isfile(p):
                    continue
                with open(p, 'rb') as fh:
                    if fh.read(4) != b'\x7fELF':
                        continue
                result = subprocess.run([readelf, '-d', p], capture_output=True, text=True)
                if result.returncode != 0:
                    bb.fatal("symoneural-cuda S2 check: ELF inspection failed for %s (exit %d): %s"
                             % (p[len(pkgdest):], result.returncode, result.stderr.strip()))
                out = result.stdout
                for line in out.splitlines():
                    if '(NEEDED)' not in line:
                        continue
                    so = line.split('[', 1)[1].rstrip(']').strip()
                    checked += 1
                    if so in s2:
                        s2_used.add(so); s2_entries += 1; continue
                    if so not in providers:
                        unresolved.append("%s: %s needs %s" % (pkg, p[len(pkgdest):], so))
    if unresolved:
        bb.fatal("symoneural-cuda S2 check: NEEDED libraries without a provider (only %s may come from the host):\n  %s"
                 % (", ".join(sorted(s2)), "\n  ".join(unresolved)))
    bb.note("symoneural-cuda S2 check: %d NEEDED entries resolved by providers; host-driver libraries used: %s"
            % (checked - s2_entries, ", ".join(sorted(s2_used)) or "none"))
}
do_package_qa[postfuncs] += "symon_cuda_qa_s2"
