# symoneural-cuda - the ONE way a recipe reaches CUDA in this estate (ruling
# cuda-toolkit-authority, P7, 2026-09-14: CUDA 13.4.1 for Blackwell sm_120).
#
# nvcc runs from the NATIVE sysroot; headers and libraries are linked from the
# TARGET sysroot; both come from the cuda-toolkit-bin recipe. Nothing here names
# /usr/local/cuda-* on the host, and no consumer should. libcuda.so.1 and
# libnvidia-ml.so.1 are host-driver-provided at run time (posture S2): the toolkit
# ships only the link-time stub.
#
# The host compiler nvcc drives is the estate's own cross g++ (GCC 16.2). nvcc 13.4
# accepts GCC <= 16 (crt/host_config.h: '#if __GNUC__ > 16' is the error), so no
# -allow-unsupported-compiler is passed - and none may be added here.
SYMON_CUDA_VERSION ?= "13.4"
SYMON_CUDA_ARCH ?= "120"

DEPENDS += "cuda-toolkit-bin cuda-toolkit-bin-native"

SYMON_CUDA_NATIVE = "${STAGING_DIR_NATIVE}${prefix_native}/local/cuda-${SYMON_CUDA_VERSION}"
SYMON_CUDA_TARGET = "${STAGING_DIR_HOST}${prefix}/local/cuda-${SYMON_CUDA_VERSION}"

# CMake consumers (torch, ggml, the probe) get the compiler, host compiler, root, arch
# and flags through OE's generated toolchain file - not EXTRA_OECMAKE, whose expansion
# is unquoted on the command line and cannot carry a multi-token flag string.
# The host side of every .cu file is compiled by the cross g++ with the SAME flags
# CMake gives C++ (OECMAKE_CXX_FLAGS: sysroot, tune, hardening, prefix maps), each
# forwarded through nvcc as -Xcompiler=<flag>; that is what keeps buildpaths QA clean
# for CUDA translation units.
SYMON_CUDA_HOST_FLAGS = "${@' '.join('-Xcompiler=' + f for f in d.getVar('OECMAKE_CXX_FLAGS').split())}"

# nvcc calls the host compiler for host-side compilation AND for the final link, and
# -Xcompiler flags reach it only when compiling. OE's cross gcc has no usable default
# sysroot, so a bare link cannot find Scrt1.o or -lc. The host compiler nvcc sees is
# therefore a wrapper that prepends the sysroot, the tune and OE's LDFLAGS on every
# call; hardening/prefix-map flags for host-side compilation still travel through
# CMAKE_CUDA_FLAGS above.
SYMON_CUDA_HOST_CXX = "${WORKDIR}/symoneural-cuda-host-g++"

cmake_do_generate_toolchain_file:append() {
	cat > ${SYMON_CUDA_HOST_CXX} <<EOF
#!/bin/sh
# generated by symoneural-cuda.bbclass - the host compiler nvcc drives, with the
# estate sysroot/tune/link flags on every invocation (compile and link)
exec ${STAGING_BINDIR_TOOLCHAIN}/${HOST_PREFIX}g++ --sysroot=${STAGING_DIR_HOST} ${TUNE_CCARGS} ${LDFLAGS} "\$@"
EOF
	chmod +x ${SYMON_CUDA_HOST_CXX}
	cat >> ${WORKDIR}/toolchain.cmake <<EOF

# symoneural-cuda: the estate CUDA authority (native nvcc, target headers/libraries)
set( CMAKE_CUDA_COMPILER "${SYMON_CUDA_NATIVE}/bin/nvcc" CACHE FILEPATH "estate nvcc from the native sysroot" )
set( CMAKE_CUDA_HOST_COMPILER "${SYMON_CUDA_HOST_CXX}" CACHE FILEPATH "estate cross g++ with sysroot/tune/ldflags" )
set( CMAKE_CUDA_ARCHITECTURES "${SYMON_CUDA_ARCH}" CACHE STRING "compute capability targets" )
set( CUDAToolkit_ROOT "${SYMON_CUDA_TARGET}" CACHE PATH "estate toolkit in the target sysroot" )
set( CMAKE_CUDA_FLAGS "${SYMON_CUDA_HOST_FLAGS}" CACHE STRING "host-side flags forwarded through nvcc" )
EOF
}

# non-CMake consumers read these
export CUDACXX = "${SYMON_CUDA_NATIVE}/bin/nvcc"
export CUDAHOSTCXX = "${SYMON_CUDA_HOST_CXX}"
export CUDA_HOME = "${SYMON_CUDA_TARGET}"
export CUDAARCHS = "${SYMON_CUDA_ARCH}"
